const std = @import("std");

const version = "0.0.0";

/// One entry per `src/<name>/root.zig` module. `deps` is the full set of
/// modules it may `@import`; anything else fails to compile. This is how the
/// layering rules in AGENTS.md are enforced.
const ModuleSpec = struct {
    name: []const u8,
    deps: []const []const u8,
};

const modules = [_]ModuleSpec{
    .{ .name = "proto", .deps = &.{} },
    .{ .name = "platform", .deps = &.{} },
    .{ .name = "plugin", .deps = &.{"proto"} },
    .{ .name = "core", .deps = &.{ "proto", "plugin" } },
    .{ .name = "builtins", .deps = &.{ "proto", "plugin", "core", "platform" } },
    .{ .name = "server", .deps = &.{ "proto", "plugin", "core", "platform" } },
    .{ .name = "client", .deps = &.{ "proto", "platform" } },
    .{ .name = "tui", .deps = &.{ "client", "proto", "platform" } },
};

// Embedded files are enumerated here so adding one requires explicitly shipping it.
const doc_files = [_][]const u8{
    "README.md",                           "configuration.md",                   "tools.md",    "permissions.md",
    "credentials.md",                      "protocol.md",                        "skills.md",   "examples/zeta.jsonc",
    "tui.md",                              "providers.md",                       "SKILL.md",    "commands.md",
    "hooks.md",                            "compaction.md",                      "mcp.md",      "extensions.md",
    "examples/extensions/hello/zeta.json", "examples/extensions/hello/hello.py", "concepts.md", "extending.md",
    "sessions.md",                         "troubleshooting.md",
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const release = optimize != .Debug;

    const options = b.addOptions();
    // Release builds pass the tag's version.
    options.addOption([]const u8, "version", b.option([]const u8, "version", "Version to report") orelse version);
    const options_mod = options.createModule();

    var mods: [modules.len]*std.Build.Module = undefined;
    for (modules, 0..) |spec, i| {
        mods[i] = b.createModule(.{
            .root_source_file = b.path(b.fmt("src/{s}/root.zig", .{spec.name})),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        mods[i].addImport("build_options", options_mod);
        for (spec.deps) |dep| mods[i].addImport(dep, mods[indexOf(dep)]);
    }

    var manifest: std.Io.Writer.Allocating = .init(b.allocator);
    manifest.writer.writeAll("// Generated by build.zig; do not edit.\npub const files = .{\n") catch @panic("OOM");
    const write_docs = b.addWriteFiles();
    // This standalone generator imports live built-in tool definitions and
    // config types, but not the builtins root (which imports this manifest).
    const generate_mod = b.createModule(.{
        .root_source_file = b.path("src/builtins/docs_generate.zig"),
        .target = b.graph.host,
        .optimize = .Debug,
        .link_libc = true,
    });
    // Host modules cannot reuse target modules when cross-compiling. Keep the
    // same dependency policy while building the generator for the build host.
    var host_mods: [modules.len]?*std.Build.Module = @splat(null);
    for (modules, 0..) |spec, i| {
        if (i > indexOf("core")) break;
        host_mods[i] = b.createModule(.{
            .root_source_file = b.path(b.fmt("src/{s}/root.zig", .{spec.name})),
            .target = b.graph.host,
            .optimize = .Debug,
            .link_libc = true,
        });
        host_mods[i].?.addImport("build_options", options_mod);
        for (spec.deps) |dep| host_mods[i].?.addImport(dep, host_mods[indexOf(dep)].?);
    }
    for ([_][]const u8{ "proto", "plugin", "core", "platform" }) |dep| generate_mod.addImport(dep, host_mods[indexOf(dep)].?);
    const generate = b.addRunArtifact(b.addExecutable(.{ .name = "zeta-docs-generate", .root_module = generate_mod }));
    const generated = generate.addOutputFileArg("reference.md");
    _ = write_docs.addCopyFile(generated, "docs/generated/reference.md");
    for (doc_files) |name| {
        const path = b.fmt("docs/{s}", .{name});
        _ = write_docs.addCopyFile(b.path(path), path);
        manifest.writer.print("    .{{ .name = \"{f}\", .content = @embedFile(\"{f}\") }},\n", .{
            std.zig.fmtString(name), std.zig.fmtString(path),
        }) catch @panic("OOM");
    }
    manifest.writer.writeAll("    .{ .name = \"generated/reference.md\", .content = @embedFile(\"docs/generated/reference.md\") },\n") catch @panic("OOM");
    manifest.writer.writeAll("};\n") catch @panic("OOM");
    const manifest_path = write_docs.add("docs_manifest.zig", manifest.written());
    const manifest_mod = b.createModule(.{ .root_source_file = manifest_path, .target = target, .optimize = optimize });
    mods[indexOf("builtins")].addImport("docs_manifest", manifest_mod);
    const docs_step = b.step("docs", "Generate documentation under zig-out/docs");
    docs_step.dependOn(&write_docs.step);
    docs_step.dependOn(&b.addInstallDirectory(.{
        .source_dir = b.path("docs"),
        .install_dir = .prefix,
        .install_subdir = "docs",
    }).step);
    docs_step.dependOn(&b.addInstallFileWithDir(generated, .prefix, "docs/generated/reference.md").step);

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
        .strip = release,
        .stack_check = false,
        .stack_protector = false,
        .omit_frame_pointer = release,
        .unwind_tables = if (release) .none else null,
        .error_tracing = if (release) false else null,
    });
    exe_mod.addImport("build_options", options_mod);
    for (modules, 0..) |spec, i| exe_mod.addImport(spec.name, mods[i]);

    const exe = b.addExecutable(.{ .name = "zeta", .root_module = exe_mod });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| run_cmd.addArgs(args);
    b.step("run", "Run zeta").dependOn(&run_cmd.step);

    // Each module gets its own test binary so in-file tests run with exactly
    // the imports that module is allowed to see.
    const test_step = b.step("test", "Run unit tests");
    for (modules, 0..) |spec, i| {
        const t = b.addTest(.{ .name = spec.name, .root_module = mods[i] });
        test_step.dependOn(&b.addRunArtifact(t).step);
    }
    const main_test = b.addTest(.{ .name = "main", .root_module = exe_mod });
    test_step.dependOn(&b.addRunArtifact(main_test).step);
}

fn indexOf(name: []const u8) usize {
    for (modules, 0..) |spec, i| {
        if (std.mem.eql(u8, spec.name, name)) return i;
    }
    std.debug.panic("build.zig: unknown module '{s}'", .{name});
}
