//! Build-only reference generator; shares runtime registration.
const std = @import("std");
const plugin = @import("plugin");
const core = @import("core");

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 2) return error.ExpectedOutputPath;
    var registry = plugin.Registry.init(arena, init.io);
    defer registry.deinit();
    var inspector: @import("tool_inspect.zig").Inspector = .{};
    var transports: @import("registry.zig").Transports = .init(arena, init.io);
    defer transports.deinit();
    try @import("registry.zig").register(&registry, &inspector, &transports);
    const view = try registry.view(arena, null);
    const tools = try view.toolValues(arena);

    var output: std.Io.Writer.Allocating = .init(arena);
    const w = &output.writer;
    try w.writeAll("# Generated built-in reference\n\nGenerated by `zig build docs` from built-in tool contracts and config type declarations.\n\n## Tools\n\n");
    for (tools) |tool| {
        try w.print("### `{s}`\n\n{s}\n\nSide effect: `{s}`; execution: `{s}`; permission: action `{s}`, target `{s}`{s}{s}.\n\nInput JSON Schema:\n\n```json\n{s}\n```\n\n", .{
            tool.name, tool.description, @tagName(tool.side_effect), @tagName(tool.execution_mode), tool.permission.action orelse tool.name, @tagName(tool.permission.target), if (tool.permission.arg.len > 0) " from argument " else "", tool.permission.arg, tool.input_schema,
        });
    }
    try w.writeAll("## Configuration schema\n\nGenerated from recognized fields in `core.config.Config` (excluding internal `provenance` and `unknown`). Other top-level keys are kept in config files but ignored, with a warning. For layer precedence and patch semantics see [configuration](../configuration.md).\n\n```json\n{\"type\":\"object\",\"properties\":{\n");
    var first = true;
    inline for (@typeInfo(core.config.Config).@"struct".fields) |field| {
        if (comptime !std.mem.eql(u8, field.name, "provenance") and !std.mem.eql(u8, field.name, "unknown")) {
            if (!first) try w.writeAll(",\n");
            first = false;
            try w.print("  \"{s}\": {s}", .{ field.name, comptime fieldSchema(field.name) });
        }
    }
    try w.writeAll("\n}}\n```\n\n## Hooks\n\nInterception points, in the order a step reaches them:");
    inline for (@typeInfo(plugin.hook.Point).@"union".fields, 0..) |field, i| try w.print("{s} `{s}`", .{ if (i == 0) "" else ",", field.name });
    try w.print(". Registered in this build: {d}.\n", .{view.hooks.len});
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = args[1], .data = output.written() });
}

fn fieldSchema(comptime name: []const u8) []const u8 {
    const eql = std.mem.eql;
    if (eql(u8, name, "model") or eql(u8, name, "small_model")) return "{\"type\":\"string\",\"description\":\"provider/model\"}";
    if (eql(u8, name, "thinking")) return "{\"enum\":[\"off\",\"minimal\",\"low\",\"medium\",\"high\",\"xhigh\"],\"description\":\"Default thinking level for models that reason\"}";
    if (eql(u8, name, "tool_timeout_ms")) return "{\"type\":\"integer\",\"minimum\":1}";
    if (eql(u8, name, "inspect_tool")) return "{\"type\":\"boolean\",\"description\":\"Offer zeta_inspect to the model (off by default)\"}";
    if (eql(u8, name, "permission")) return "{\"type\":\"array\",\"items\":{\"type\":\"object\",\"properties\":{\"action\":{\"type\":\"string\"},\"pattern\":{\"type\":\"string\"},\"effect\":{\"enum\":[\"allow\",\"deny\",\"ask\"]}},\"required\":[\"action\",\"pattern\",\"effect\"]}}";
    if (eql(u8, name, "provider")) return "{\"type\":\"object\",\"description\":\"Provider IDs map to options (baseURL, apiKey, setCacheKey) and models overrides\"}";
    if (eql(u8, name, "plugin")) return "{\"type\":\"object\",\"description\":\"Plugin IDs map to that plugin's own config, checked against the schema it declares\"}";
    if (eql(u8, name, "compaction")) return "{\"type\":\"object\",\"properties\":{\"enabled\":{\"type\":\"boolean\"},\"reserveTokens\":{\"type\":\"integer\",\"minimum\":0},\"keepRecentTokens\":{\"type\":\"integer\",\"minimum\":0}}}";
    @compileError("new config field needs a generated schema definition");
}
